---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: descheduler
spec:
  interval: 5m
  chart:
    spec:
      chart: descheduler
      version: 0.28.0
      sourceRef:
        kind: HelmRepository
        name: descheduler-charts
        namespace: chaos
      interval: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    kind: Deployment
    deschedulerPolicy:
      strategies:
        RemoveDuplicates:
          enabled: true
          params:
            nodeFit: true
        RemovePodsViolatingNodeTaints:
          enabled: true
        RemovePodsViolatingNodeAffinity:
          enabled: true
          params:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
            nodeFit: true
        RemovePodsViolatingInterPodAntiAffinity:
          enabled: true
          params:
            nodeFit: true
        LowNodeUtilization:
          enabled: true
          params:
            nodeFit: true
            nodeResourceUtilizationThresholds:
              thresholds:
                cpu: 20
                memory: 20
                pods: 20
              targetThresholds:
                cpu: 50
                memory: 50
                pods: 50
        RemoveFailedPods:
          enabled: true
          params:
            nodeFit: true
            failedPods:
              includingInitContainers: true
              excludeOwnerKinds:
                - "Job"
              minPodLifetimeSeconds: 3600
        RemovePodsHavingTooManyRestarts:
          enabled: true
          params:
            nodeFit: true
            podsHavingTooManyRestarts:
              podRestartThreshold: 100
              includingInitContainers: true
