---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: pihole
  labels:
    app: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: docker.io/mvance/unbound:1.14.0
        ports:
        - name: svc-53-udp
          containerPort: 53
          protocol: UDP
        - name: svc-53-tcp
          containerPort: 53
          protocol: TCP
        resources:
          limits:
            memory: "300Mi"
            cpu: "250m"
          requests:
            memory: "50Mi"
            cpu: "100m"
---
kind: Service
apiVersion: v1
metadata:
  name: unbound-service
  namespace: pihole
spec:
  selector:
    app: unbound
  type: ClusterIP
  clusterIP: ${UNDOUND_ENDPOINT}
  ports:
    - name: 53-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: 53-tcp
      port: 53
      targetPort: 53
      protocol: TCP
