ansible_become_pass: ENC[AES256_GCM,data:uuucg7iJ+L8PGjWMQ3REQg==,iv:0hIBlfmG5lfnLRxF7YJP3SS5Q6HMkKlkGHIg5/11Chw=,tag:S+HBN13lqp+WRplp2EvK3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QWt3ejRHaG85R05QU3Zy
            aWFzdWZCaytobU1xeG1Cd2xvaXNzOGN2MTNjCnU4Q04vdkk1RVNmMS9nMVJaZU9l
            WFJiSmFVaFNRdTlyTlN4YkE1ckJkWjAKLS0tIG5wV2Urek1GZFlBUmVHZkNFTnY0
            Z0ptZW90cDVndCtTKzZIVm1kOTQwME0K4prco+39IDXue2Ti+VQ2oxXEMuU34G2z
            CXPyvYJZ3E58xAN3sm0b9XmcPCTcRM59z61L+dzNqM6iFcMwqgC07g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-26T06:17:18Z"
    mac: ENC[AES256_GCM,data:vfvC9bnCI1eNMDPsJrY29Py3ts5QiV2kGjuuMNg9CjWw9pL5qNsltrjnocxmrbBXOTIgWsKUel7ACy9KXNb4RoBv7QsDhKVnfNWhw2zIKLkXPbk9IhNUA76VNiGbRbkBcj0PWccDsYO+erYufJTlmh4XZTVic9/fSezUCmED4GI=,iv:N0l9bc7UAVqoZgHR9S7EOWT08YjjdAtEZL65sd5CF+c=,tag:XnxXdbNplVEkpovIVUGNjg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
