ansible_become_pass: ENC[AES256_GCM,data:FWo4B5hG+TmsAv32+x0EOg==,iv:1dQzrOrff6laE2lcsGS6akqVD4Kbc04zcmWxo4gfB94=,tag:XQZkSgdiihS1sWxjb7obPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UHBjWHpOTStOclJzMHo4
            YllEblFETTBFcE9TaDJwMWRGTjB6VU1OdzM0Ck1BTldseEZuWDUrUEd6enhYbGJC
            WUQrTG9XMHphVVN2Mkg5elFZaWExMHMKLS0tIEhjWWdxa0hXR0k5TmpKdmtnODBI
            cFI1TGJoYVFtMHdCSmxDZi91WlZ6VTQKOQ7kXt7IScPWRnk11psk28OTsCvyVM5F
            ub6Bo/9pDwIRIrIYLTz4PJdjpuSnJgpP6zxel9BF0jCLM7/A9L33PQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T18:31:15Z"
    mac: ENC[AES256_GCM,data:jInAeV4Rd2t/MAMTCdZInv5AyJg0sZsTNY+dDYQghucvRI0nx65F1wrqg8wwurfJmRXj8N0o5w7oKGBGtkk2swlldMzHLcFt0sDepWRMev7MSoVNSQnr1yI+ZiZHp3ouJ2y1e33m75sdTwo2HW8751W+BwP0ibqSBPbFkRqjc7s=,iv:ADNVqLSs98o2F7kzW47MmxtECyxVWpOFsH31O985Yl4=,tag:roE0A4RTP0Sd30j2+mgaGg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
