ansible_become_pass: ENC[AES256_GCM,data:J6hVAUFX+OamwFa9uQ8bEQ==,iv:S9oRL+nGn956WO2kmn8epL8INqvhOBlMMdAYCbBKa4s=,tag:v9rZM0FXd248xUmOqhRF8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqOS90dURDUHZRMjQvcFFv
            eDExSGxpVFlPUFg4bVR4MGlkZ2Z5NWp4Sm1zCmpBMnNGQ1dJZUFCWURiYUdmZlo5
            N2lHWmxpZFppL0g1OXVqMHdzSVNMYlUKLS0tIE5uRFQxblhiVHpoZFB3U0cvUXRZ
            Ym8ybDRNWjZXVGZnUUxiT1dTcTJtNWcKBEvZd2rpY5XQ3Lw1btxXga2EcT6MrOFP
            LFDeIlXQ/WCVc2Smlyg5trvxa5XtM2Q6AJduUCSgZWVe+mKuP4AcfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T18:04:55Z"
    mac: ENC[AES256_GCM,data:FNG9TgO5Oya2RxLEX61u4Bd4CfAbxe4QrMtjUXJypwmANhZNY93/rbmjNpn/egDF505w3LUY31kPUZiBxAv6vwoxgWdFa8HJD3KCtPxpVGY0oS69/XgNh+mn8DG0+qvwk3sWEU6zGTAhUX8eXlLq07V+QYymdPpi/MFhDccy2gg=,iv:dCjVEhE3eje/7jgRohpVQXlYJs9rr0M8+eIDTTikqn4=,tag:RQOdqC0ZX2jqRDB4jdYsyQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
