ansible_become_pass: ENC[AES256_GCM,data:MiUbFioUgKsOZWrCTA0twA==,iv:BHhw1106aSciX0SzUFQo5HQD9TRfy0K/RyGKtoM0FzI=,tag:ZabvI7XtqlHaqZGloDhlTw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWFNsQ2t3R1lkaml0b2tC
            TDNXWEdTWTZVY0FoeGV2MzhqVW1CeVVvSTJFCjQxQVZYVWdCMzJVOEZQUDNjVGxn
            MUxhMCtMSWJmTEZ3QVBsMTZqbWhIazQKLS0tIE56Z044eTJyaDJUT2YvYnNaQW1P
            bFFIRlY0UkhrUDM1UDNSNS9jekpCRkUKNPO6bzAnbPPBXJUPZdOogUiJLaWe4o1H
            oEWXCMDGGO4qMnV630ZzAHnMJp08E2+gD5YIMpH/cQFj4g8mDq4EhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-01T22:41:30Z"
    mac: ENC[AES256_GCM,data:GxtuTKxefQPU7wwU6F5jiA2Y2SwT1VvPEC3JLH34cxpVycjijMlEO+qkPJyX+NeVDM6jNL67hx1C/oZBXz3Zubm2FMvjCCKx2kj8C2+cflCvLScbx8MqXhxSwZEp7pQB1EO49+c2SdLnmfKydIwNGahbqt/k8/Jxa3+J0AYs/2o=,iv:jSTLRreijtr/qopyv70yWuMlvOdSQra6ZCKB3l45qSg=,tag:ffIeztR7ZwTtF0nXuZUvAQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
