ansible_become_pass: ENC[AES256_GCM,data:Zwy70cXAaD17GhPwI06uAw==,iv:SUYcUH50KxNCn6OOuGmOHYcYTlrPtXZzT+DA5pu/8mQ=,tag:3YR9D22yCQcQ9zMvNcgwNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMTVTMkx0eUNROVRQZFFr
            eU5RWUtKQkJOSjBxSmtIZVdqUjBQQVZkZ0d3CmExcmhPSDc0QytObVJwVkhSczE5
            VWpjaFU2aGV5RHp3bHlhUnBnSi9hK0EKLS0tIEZ1QlJySGZ4R2V3QnNtM2Z4NnUy
            cVN3cDhkcU9DSForZlRnVlZESC9nb0EKqKthNBqdlZxeM3FnEi6340HFiZ5IjBoV
            D7bnEKGf6oQU/OdI+4+KyZ5LamF8kWnGYTEizfLdo5Phf7H18d48sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T16:15:39Z"
    mac: ENC[AES256_GCM,data:/MFseiYkC43PlpLdyitscbwtCpdIydpB6807wyUxdMK+IjK5bX01ixPExXMJ0qoLv/W+8HUkxtGMBJbKbmTsxoqbfLQFfw1KSQf0TKWVkiQ2QryrZYN4y9zYDxzURZMQB1Ow6FcFFNSbG9BlrqFyXr4XNmmSOpxGgZUOiOq4OMk=,iv:h6mIQLvjL6uLimoOtICAOuLb7JG0PR4zUeoL9JmqW18=,tag:KroABjM2D7H4Se8wKfl3wg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
