ansible_become_pass: ENC[AES256_GCM,data:3NOutPA5GcTua9CtzotKnw==,iv:6MQuDcD7D87dSWXfHUqSP7COSgbCUZRPSZ/LWNj11hI=,tag:fJYUD10u8gUxeGwGC3u9pQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVmdFTm1NZElkdkwrb1d2
            Yll1Smp1ZVhlYUZ2T3BnU3VJSjFweDJGN1VrCk1iS2dFdnI2NjFZTElSN1VUcDdk
            Um15YUJrRzd2cVZrWXl6cEVqeWYxbjQKLS0tIE05aXd0eEk4dlZWL1EwRmxONllR
            dzB1dTdUZ25kVm0zZzJnZzNzYjQxR1UKjRZ790MugdqMi6HaB/8pG4A0KMFoqjVF
            ppa8520jr0rrzoI8nPU0mAf0nmzeLLrhIMyNcbUkZPvEo5ceSxnhvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T18:04:55Z"
    mac: ENC[AES256_GCM,data:ssaGcRFTGNDhJuo644OBlnznsZ8P4KhXQECvjrcrb3bsWUu5pJhWq0ADez6RkPb6AxS/BwSmf4gD3vS+QzUyq6S6wuY7NiEBAKGF/qXcIJFCsPPieBtN9GF1c0USVRStoewdKZdz99HnFPZqNhJMg9ZVGqKOIh/CAkwM304vSDo=,iv:oOldQK/DVMnEKXpBMllNTIlQR/JirZBWk+RLh5m+XmI=,tag:MiSM+ndiIAbTV6frtwhu8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
