ansible_become_pass: ENC[AES256_GCM,data:uHfoHijE/z8LOxV+I7b1XA==,iv:vpVAtbExOVlUaZbSjvLkZ0PT3VH55U37/8jYgQvsDac=,tag:wOA1OZUgI3LK7Tavq1zx2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSajRPdm0rdU1McUV4Yk1M
            cXZ3N05DcU1ycWsrZHorSWxlS25WanM5WWxRCmF2VEM3bXY2VW9kdVhRUW5EaWsw
            YXl1dFZpTEFaNzJ1OXF2NlhaN2VUalEKLS0tIFVqc1NXV2tYV2dzRmpPdHI1OXEx
            SHRINUVKV0hRSnpuWkk4NFEwSlFYVnMKR9VqYrqJBvyTO9ItZ3QLXsUT2qs76bNo
            K196v9JQr2CZKWkNqNkHqsXLE2E/uctD9GPqix6d/g33/Ai5+iqUvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T18:04:56Z"
    mac: ENC[AES256_GCM,data:K+sCD7I/dSDwqbk8vThqY4zyaiIX5keMOCCar7bZuak4oH9FBuSbhez54PqTWNfN2ooV6QCAk+IYJUFWRKUeJ8FK8O9EnZAnCpYVcvQ/Ij6Flz05KWn7Vjct4rGSnDubFIHhpjmEdexAJdkXAqfDWCKUz3Zl4oCx7uoCvIPyPkU=,iv:3TtdLvyDv3vjDAkK4lCbugIIJNWzN3f/3vWu4N1Xayg=,tag:eObXIbrpV6vtKtM+FxgdzQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
