ansible_become_pass: ENC[AES256_GCM,data:zmdbidMM698awrosic6djA==,iv:vlKhDOtcYM5E1mU9s1y9dFUfD6jzbunUFdr7zz38sQI=,tag:HLAxtJ+YdbpH4aU3TbH0vg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaTZmZEZCaDQxZkhZbWRR
            dVo5UEZuMUFnSGtuVXdMM2dKV2cxdTVWN1ZNCmE0T255N0RxMmdIT3U5dE1zemh6
            blJXVkhDSzdPb0NyTHNrSlViSFo3cXMKLS0tIFdtWkgxVDY1MzNEbWxXSU9SK28z
            aytZcEkvRFBBanFlazIzWWorbGxhZDgK1DvFTNFyt3y16Zzx6Tei7wcoU7a9qEX8
            uhSC4WnmBGjW92GCS74EVYOxQAmoPUWMjEQ5jJgN2jSIaIHrqcRKIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T18:04:53Z"
    mac: ENC[AES256_GCM,data:gKJYmEFgW2LlaDCyUj727pp4QAF/qUNYf6h0c4f+dvhVlPw7lIlRa8UDt2L33Yn7/UEzEo3qDqTKihJavnl/BFCTCbCJm3a1irApZ7j+33vjV5Q8BckBYa5hwMQuZ9don3UtObwbGbGz9Jq/bAMggqm5kQAcvHA8uW5RGZPfRFw=,iv:J6YhL5G38arhOEqpbpuouWpaa3TQ6Yfgmq2ydU7Rnj8=,tag:9RRonhzyDkD8BTd+1kRCkA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
