ansible_become_pass: ENC[AES256_GCM,data:XQ4SRGeOAczEaTQ9Ld4kyg==,iv:0YOLEFONSj2B5Nvg+6rYJLmzGCrIEMoiIaMeXw09gJ8=,tag:u5f3ogeIQNT6NIISvoBQsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQXZwZFN1ODVtUmtvWnhX
            NTl2c0M4VDRGWjFDdzVNN3pUdlNQNjF5L0V3Cm1iNkNnMm55VkM3SVJvTWJzSWkv
            cEo4eUJuZGtRSXNvV1JoMXM5eFU0RlUKLS0tIGNsK3FRU3BHM1BIL0FUV3k4aXBy
            ejNoTHNFeWtZMXJmMWNNRDJRdmdkVnMKGILRU/u/tslfMPP4fcHTGbQqjXZKJzQE
            AUBecuwJX3Fl9Jg7Hmq5PyDuw2SSNSo7dCHu20Mv41ooS2t7F5tu3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T16:15:44Z"
    mac: ENC[AES256_GCM,data:xIv2nDGmCysehh4ahxUOQ7Ndzww2py8w4ApsewTUGM0airH4tnAcfJjrEIhLYqMwGdslxL8Ic2yK8O1+nJYLUrBBKtoeeikmjvjAuy03Re9wtVr5J17UfLz/UNuj3o7XcxH7C9SShwtrZc1TN3jGTD0H200If5LPrno4e85rWoM=,iv:vaHb99koIeR9opfD/L/s7Rezz2+bZDWYw+AUQ6w7T/I=,tag:kKcvgiCiJwDf16RS5Z+Msw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
