ansible_become_pass: ENC[AES256_GCM,data:2jS8zS3JhO+6C9b+iT9gaA==,iv:kFy7PFtIWnuVFAiBjAvStzWrqvI4EQJIRt0TkS6sLRk=,tag:jV6v8ihhune4JusthSPr7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiTWhNVmpoVFJCMmUzWUdP
            dXBnZS9rckMyNjBjZnZVaDNQUWpsd20wdkZvClFZWG5oMkxsZDhkM1RiSVMyTHdD
            Q2RET294U2txdUgwamo1T1JjK0E5bkUKLS0tIG1BOVRndGFVSFJOZm41cXhCelBR
            eTFZSmFaU0x3aUMzWE9OZjdSNnl5RWcKyiS0kZDwNV3pANNvqxomMlIZEuej0SFV
            xr6fHGrFaezCIbPP60tqYIjOpQqUijEZlTUSm4hj71kbNB1Q4E5Qpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-01T22:41:35Z"
    mac: ENC[AES256_GCM,data:vTM+aQ0vwtQfWt/QgDWg8PwBvQz4Q4nwKlcqI+P27mR7L+poRa0vJI/g3+L6LOfCGkBhBHAupJixAYW/pTRlG5453RYZ9oUV6Qa7OtSM1ouDwVFee606rFnksOdAGLuYzv3JYei1p3GajHq61UvkF3UZFo4/p00+yBkqZljEZwc=,iv:T5OSsuIpswmlZANPThxx+Hd9NeRkumI0fPSZyEQ+3hk=,tag:vht7blhGNR/CeKFYQqujPw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
