apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Zu9YcwB89CSgf3m4RJ60goFZRI87lbSA,iv:18uYNeUBHLqGfckyVnHdVZRUckkJr+cJfQeQP8NpvTo=,tag:sH/IeErPpRcVLGA6ovJE1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZFJpNmRrcHMycjF5N3gw
            MFFTSGk2VjFvOVZvbkJzZEhHREJpZW1ONkc0ClBKbjEyb1FHejNmM1dWaExCcHYy
            OGhzWE92NTF1MFFWUktRcy9NRTRDeDQKLS0tIGV1ck9XQXpTbEJaNUFjRHBoUXFK
            VGFnNnJTTXFXWmloQzJ1K2FvblRZaWsKRKOfN5F5O84W7dl4vV0KfSnTV5m1+itd
            Z2IPbrT11UAuykxMRhy1AV3gI85NRSQ6MiN539Cw0BLftnbhJdjuig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-26T06:20:17Z"
    mac: ENC[AES256_GCM,data:goRX+A0xgOVUEChsx8PmpEd5d//8Bo4SKLwiwZwzpT5dtmjtHPsTS+DU/esLqPaD5valEFOx1dFCrRlfnl2/PRRPI6PCwU/TSf8o5kpYcHUqfPPjmGj4sHxu2+vdtuXIPpyq0ojTMGMEyBzq+QbYD1j1lw1GsR0DQw1ZE7QZX6I=,iv:lZlgm/xHb9dMlXe/P0XCGi+EjLYFxjXrkdYogTcU2kQ=,tag:pSRP+0xEnXznJr3doQQMCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
