apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3bOBiFtLmSc0hTpaSJ/IDHO+eLyIjL6O,iv:rrTr9p55qfzRvAt1ujZYcI41pPVv2kEVaDF13LB6G8I=,tag:sfbzfsyvykiMJJaqS0uzHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSDVHek1mdDg0aHFIcms3
            YjlhdkZaQnhkNFhYdGpEbXVreFlYVGd1TndnCnh0UURHbDd0eklYNzVxOXVUU251
            SlIydDhvMzVlcjhRZnlINTFvRkRCVHMKLS0tIE9Kb3RRNmhJdEg3aCttbVh2U3ZR
            VWU5S2pQNndld2JQNXFlS0pyOXZEbFUKJpE5BpOfWL/e+TIoXxGQPBaeafRcGx6T
            /img/zWWPx81Vn+ayV70MDAxdLGL/qagXC4Y5y2OAbnmeOFFHCdqVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-28T15:55:32Z"
    mac: ENC[AES256_GCM,data:GF7glRy/7VaeQxybYDnmfxYNijf4nwCfisvHqRBOf0mk3CdPZUy1Cp4hwGph1xe9iAyT+/gPnQgrd3XmWtffo064HrLDI8fRnUMC8+uy1WnrKFfLGyKzsYX6DxQAYfNBT3JQpgtLwiKo/QR22qg8EL/MvwUblnKZGwHk3zCDjlk=,iv:+BYBvTFW8/vBsC2urJ5mgm8MkBtWDkweaIDw6cjuNcc=,tag:j1ZMK4NLVOINlwxdrrivXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
