apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:fMFI+VNiNo/WSfluHAuRT1ExEltWX1S2,iv:X166vBJyPbKuR2oGMVIXajL8LiYamptLrr+BI3BwG/Q=,tag:spvNA9jyWarLWwvfaoYakA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdTBHejcvaUZ2ei9wNENO
            YlJSZ2YrUThxbW9LSW5EN0N2NG9FL0VWbG00CmJHOTRDb3N4c0JHYWdkODl3dXQy
            RDY3WXVjek1GVWsrcXRiNktKRExWeTQKLS0tIE14cmlseWQwRi9NZFRoVG9ucndO
            N1BqSm85ejMzTjFxM0ZkNWtKUVFONjQKlt69JBc1Sp5g+KVT8udPqMop5lhav2Su
            Ml4nSq2DioL7dZ6HDiCo5Avxr4BKmuypdVi8PVd+djuIqKXNKSiPuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-03T16:18:48Z"
    mac: ENC[AES256_GCM,data:EZi6BT3T2eqhsNUXJVELlflBwPYM9wsN2kE2ZMJ3R7ia78CqeHxXh4BDK7imkw1/9PY5SxoIxpFK7HC+AC/YQt/DwPY4vvj42AV5cFiyDC/82PY1PyV0BAPLoHqVJEWbXaqysvlScsLWQh0I7UG++iOiMjR6FDZVsE5xvhfqyuM=,iv:A1RzfOHEzC2n/zcmGe2Liz94YJIrNFF9KavpFiRT1l0=,tag:rB9CVbaeHFDAKDqo+ai7yA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
