apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:CvpjA4VJGQp43frr+yQpkj8ItYmpUbzD6gEO+V/dvMg5ZuVCBmasJw==,iv:NDfwZODNAqKQlV6nPcn33yhoGsihX1N4+u+vKsXyj7I=,tag:l8E7S3dVCfxG4f0KG4d71A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QzhJUGVzY1JTUlZMK3Qy
            TXBJWWFMSFNCVkE2SG5BSE5kaGpkRk9oRG1VCnA3OHFJRG9mcG05OFovT3Q1MDND
            UDBrU3lxRDhET1cvN3NhRlZIWndETUUKLS0tIFdkVXpjMlZiRDJBT0VtSVcrdm12
            OElEUHc1N3c1UCtwYWhQVHVnTTdsUWMKWNPeocFuJts3VYPht46HtQ/bdhDd4zpQ
            8eY3rk85U8Ee0g5qBgsQJ12I21F10pTHSy8vEZHSs89vwslA+9xL8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-25T18:34:07Z"
    mac: ENC[AES256_GCM,data:NE/jWfxlCAEXdWvHwUkpPuazHjp/U1mbGnQbbKyvzbnkLnJ3p3KImndDMxWUQQGnFff9Y+Xa+C1caXrnIvEWFRarNpMSzATHIYhMNmkTd4+C2uK0PuUiVWDzQ/8ah9MzZWml8Z4PuFqLkRF4pxvDkg6iBdCNGwkXXyughuSN+QM=,iv:DTaMYQl4Pb71K1CuG7w6GqT3TOO0DBFL2kjQkHhL3GY=,tag:tL6bb4WEAlCEqoVsZfMeHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
