apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:z8Vmcr3vaMwJCTV6tNGPqhcfRmPdZN+bp/iVtYIQcgAZWYzOeLkGNA==,iv:9WK0bq6NRUKeMkykZ4YOoZNr0qix2WO3iP2JsbEN9Ko=,tag:aa85/G7OiJ+fKuNQf8jCqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYejJVdm9mVThZWVVvTTNN
            Mm1GTS9UUzMvcW9Pd015VHZPMkpjSnlmQkZzClExaUdzWERlOUlKeG14eUV1b2FS
            UEpKL0V0MVVjR2w1Ujd1Nk1aMFU3aXMKLS0tIGxhelVWTWVUTncvTGtDWWt0NVRU
            TU0zQ2kybGxoWFc1ZkpsU29HeUpydHMKP2Owj2hA9pyjabF4t5GZCI0pJpS+nnt7
            VLWQptkQKqfsmzHsqxuImAuMPnOSOeiNjgwkRLqU9MZMOvAeTfOVbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-26T06:20:19Z"
    mac: ENC[AES256_GCM,data:yidzwKlAf1jT1JZ2TxDsPSbVxaC06UmiBlwg+upIMDLQAdPnxY7RNnWKnHnTKuvc9wa3aRbfAjwi22/V1XXKya7t0OBbAEeBVylEdE6cbd4n7F5mjhc7igw5C1tfwaU8kLMi0SkLHtTdJsuHcqw68sWhqOY4Wgj6Z8vfkpJE3vg=,iv:VSjHzGsRQzIU5vLsId63w7NpokYPiTTWbzQFk+WYu+U=,tag:1Hk6AkQ/R1qW64ivCaWL+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
