---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  dependsOn:
  - name: longhorn
    namespace: longhorn-system
  interval: 15m
  chart:
    spec:
      chart: pihole
      version: 2.18.0
      sourceRef:
        kind: HelmRepository
        name: mojo2600-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    nodeSelector:
      storage: longhorn
    image:
      repository: "pihole/pihole"
      tag: "2023.05.2"
      pullPolicy: IfNotPresent
    replicaCount: 1
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: "${PIHOLE_ENDPOINT}"
#      externalTrafficPolicy: Local
    serviceWeb:
      type: LoadBalancer
      loadBalancerIP: "${PIHOLE_ENDPOINT}"
#      externalTrafficPolicy: Local
    serviceDhcp:
      enabled: false
    https:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: external
      hosts:
        - &host "pihole.${SECRET_DOMAIN}"
      tls:
        - hosts:
          - *host
    persistentVolumeClaim:
      enabled: true
      existingClaim: pvc-pihole
      storageClass: longhorn-crypto-global
    adminPassword: ${SECRET_PIHOLE_ADMIN_PASSWORD}
    extraEnvVars:
      TZ: "${TIMEZONE}"
    DNS1: "${UNBOUND_ENDPOINT}"
    DNS2: "${UNBOUND_ENDPOINT}"
