---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pihole
spec:
  storageClassName: longhorn-crypto-global
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
