apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:r5CCOxrYhinMD075z64hA3MXbf9p,iv:RXBYsDhaxN+0511DypDcHAdgjgfl1gSrgqUj8PtYeXU=,tag:iYaZqq9J2ct4nXODSXnlvA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:yg6zuPZZUFO59jrj/zAvZIe3ux6nqFU1nOnxet4IVl7tQrfi,iv:e2sJusU8bnt/d457roARMeaoJ/RBO5GshpLlVQYu9kg=,tag:TS8OWgwTzl6mpfTQf1erCw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:hZnNbwllGw4d2g==,iv:KR79EhyeZthEQ74GgznBfBXDGBdmfRzmgKS/Pa5w16U=,tag:2ML3ONhEHqnBrbZt0mKi/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZ1h0TTN5WXNyN2pRc2NC
            dlQ0Y1lvZXV6N0VjWGI1Q2FzUnJaNnJBNFcwCmdzOFRJekhrY2paRGR1WjIyVEY5
            VTFQTldrd1JJNEJmL3k3LzMzRDU4M3cKLS0tIEVjc2tiTGJtVEw3UUZjRTJCVkFh
            bXdGb2M2VGpjMXlKRlZ1a1AwVDNMYjAKjqKKw7pfliyLKVAuHJTuTRLNEu9dYMee
            Yklwr7/NVj0JKVaf3AB4FSqYAiKK0AlxlxZ7wcDwoOt9IZHZt7/IHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T18:08:05Z"
    mac: ENC[AES256_GCM,data:NeSSi/V25ZYxehbDMFLkmAFfP//poe+ojYB2nrDm0Ig5BgX2k7Eani+KutN1R8+6iiDK5a2N+xQUxZR+wh3wMZ3zZQMRyR/nVwsTD0KMDVnVY/lsVxFdAawvlGefk1XYhySr/yvHhMdFegxa0GKrARG3z/WX9tMC+IQTNesWpv0=,iv:1D3kBPJwV0BcmN+1OmC4S3qS85eoXL3G8L/aRLVpfhA=,tag:CTFA/r+L40UuYRj65mw8Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
