apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8/gf5x6b/47iFrnNW0q5DMhy2ZPg,iv:ph7pT5zBwegXkJ80CgIB+bZJgzTjjsAUyJqGLcARS7o=,tag:HGRkMHqCV4GHyemf95kwHA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:bx5e96n4gxXdqTjDSYv2pCWmW6hM7Av51RFYbdHEACFMuXPD,iv:EU9KzuhOsMkEaNBC5l35sS9yRVQ3WbiSBKT7DcFJM5s=,tag:gw8eJfrmFcxPcfULnqAiHA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:EOnQMoTujFE5lw==,iv:eS9yn9OrCUVOHxIuu4uK8RobIDmZpRD/y+xsm2OQj/4=,tag:6lHIP/AnzPpEsy19mebKCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOc2RURVN1Tno3Q2JKOUJP
            Zk9oSDhrbHVvMTlXOEhaTlZtWjlhVkhhZVZjCjAxbDh5d0FhUXJHc3pRdEJsVlJO
            TFQySHR6TUh2U3ZGZ1BiY2lCa0FmODgKLS0tIGU0NGlwV1Z1SWhpbUQ3NDgyK3FW
            bjNBRDZGK2N4bVBhY0RnbWNWN2VlSkUKIbt3pZ6dK4WHHZSHjWju4ZBvFSWe3pvY
            8K6d5ap5FICd14Z/hJ00L5u1Pv2r6jbVC8UWWzRfPtBB2r6NGdZF0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T16:25:02Z"
    mac: ENC[AES256_GCM,data:g1OJZWzBGJi6sgqgmMag6Niefv8c75OwMLOp0TqryHIZEtRqs9Fq2LiM38s3EKCmLCyf/g4SufDtQutqlF7Zzq/IZE1lCPgQogpJJKo9LMjx9KllIUF7uoVZgSBx6zvsKoMEIjlT/bsC5y0cNtdOVwHZGVlqlm8FRYQj8Fooj8Q=,iv:9jfu4rTEJG11dYT+Pur3qqMLGWf96/xK8rU0cItnRdE=,tag:wjIjE/k7e0CP1dyqWLLKNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
