apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/zouy0LlchdJHbwz40BG2zDqRJJM,iv:IpC6HWcGlMnn8L5W8sM/t9pexk2YN5IPJJdMKSziOOE=,tag://edAY6Cv4Ha0lD+XEhiyg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:PELkdFq/MLAuh5Lmkr6y8JIh171IfF65WpZqIKccbHm8SOoc,iv:beiE+27BBBmbBHHWWSgvyGpGB/lPLCjSkPwBo9O6r80=,tag:rDWWn0VKhaeM0k9iVxfcoA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:9lHGu0btEbBudg==,iv:iCBO7zO85TKkaeeXYrxJ+wKDj3RafV4jSwEUKO9tKTw=,tag:jLKoz9L6ZJII6O3MQrjupw==,type:str]
    SECRET_PIHOLE_ADMIN_PASSWORD: ENC[AES256_GCM,data:LuroTTrpg5GRkpcsqhyj,iv:fpmwID+XX8WREf+h+E6RG4Po9UKf2Q5X6l4ZZfGOBD4=,tag:N6fozEpwRpzOT3VG/FDLxw==,type:str]
    PIHOLE_ENDPOINT: ENC[AES256_GCM,data:MvkHS/Madm+T8Q==,iv:60OI1VoaVbI5kTdv6AQIy+SHk59TZj4PKJsvJDsFS0U=,tag:Z+y4i5XyIhZfEOMJn0SGIQ==,type:str]
    UNDOUND_ENDPOINT: ENC[AES256_GCM,data:sTfVD7R83w2trw==,iv:MHooDQXEJzk+PpIZauvpNp+NQKpxskLOyCZ5JzMdOok=,tag:KJw3BqVwu0ufgooVIuC80Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcjFPZnh3eXE2aFU5UmxC
            RlNYalZqQ2RmNUZWbGRkOFpwMFdkWFlpNW44ClExbjFvbjZpS1FHRUtXZXJ3NVM0
            R014WVIwRHZHNkI0L0NXa2tyLzZ5eGsKLS0tIHZMdnJUazhjL0RZY1IzamFicFRW
            YjdRVVBvajJ4QlgzSmh5eTRMRVVGQzgKU+IQcPtriipy7vzI4EjyT875YWbvlpYa
            1BEBHhY0dETEHDNkTJa4TorwIKX3Jv4NR5L/r5cgj52/oOP27s6szA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-04T03:50:53Z"
    mac: ENC[AES256_GCM,data:v12NMWOlJDbJQLeA3MIJy5nW/k392JSclh0U88qEu+ASeGfk54D0d6GB8bml1FPeh16JPJwLKsGz7PMYUg+Djrd+G9jxBGFp02A7IpRh2+k3XnEVzMfLlQpaV/dLZtpYGqna+LUMsoYseN1nu3R/PfWL/j/6SF72YQPGYv4vagw=,iv:EbwlBx/QCpXVsATnzWwsO1F/5yiWVr7kWeM4YM9u0zQ=,tag:viHLDVGqRFBbJ3zij5C2gA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
