apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:aRRU09qsh/l74RIPJxAySvMesJQqfj9uFADMuYbNJ2gbIeRy,iv:xFEbu4mNFTh1IaNPTTaXwWna2pn3R15TxG0WiWRGON0=,tag:o1Q7gbJivCwgE4QjKqS/FQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:xMMQwe51UmFFQvuAK3Q9ON1/CePQXdOT09xEA52w1MpW5o4EqM5yHOG/RLZZAVPFgiWz2HdmRjgRH/7IuJVFSngT+1qU6HrakthDWVcSjJE4xsYlgdH/IfZjnc0+tYM22lGLPkuw7Reh/g1gd+noi/zBND9NC+FML9XfX92mX6DXuQxYhP4PWYwCaBYv6YEH3i88BYSvtB2gCp8HVjylIPWP7P+YSIOl25emnReLkQ==,iv:v/clAeVhksuSNr3oxIRcJ7thma1/TWZsW0f7z9vUSfw=,tag:yU6hqjdFBEGSuNIo3QX07g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAremVHWml0VlowRi9TSnZH
            dUNTcE91RmYzOWpiKzBJYUM5d0R1ZVpFSlR3CnA0b0wwQkw0VFpZenk0T1BVN2dK
            MVFWVDMvcHJITEY4VDB6SjJpZDV5K3MKLS0tIFRpN2pVcXMxcjUxWSs5OVZ5eHox
            dE9jbkpWNFF2V3NqWlRpNDQ0RDdmT2sK8yNrvy+/Gugt5jT/rsD6LFR7ERjI/Bm6
            idR/cK9ShRv1ljxSl3YD6DgvSM28Mmhea2QqExoh2I2b4MEbXwF++A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T18:08:01Z"
    mac: ENC[AES256_GCM,data:tW7AhuvTOC9ipi3nSgckgtzlymqXqmg7j9mbsxg7jucmsd1uu1jYAKQh3nJS4K5cq/Qn0FhwJeswyOzVUIYJlgX8fDzQb8E/eqnM78o+vvmMrh745gUnAgH0n0roqpx2s/wTZClc79DGC7QEhyWxEK51bZ1uxAt7IxGs0OmZqjI=,iv:Pr7G4AGn68W9OD2LUaf5lOvx1HJZvlH6Ej4exO+TZ9E=,tag:3M/R3Q92p/FcrB7yQWI+qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
