apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:XwWGomqewH/Q30kJyQJwCTM2EKDimgTHmrGwgaQ8z1rF0IzH,iv:veiYwEAccRiZRL0CDrb9o8+WNjaI/2grEF1oeHGoC64=,tag:Jh34935hnFulvKcU25M5Lw==,type:str]
    credentials.json: ENC[AES256_GCM,data:ikmx7rAXPWyjZLLuDJB+l9NmdCZDUndz8HVs3cVwXMqfquee8suNKWMMsadDV+Sk08m008lZw3yakUPokf4LFMBHUr0BRyhFPxFbkFDfs73ca1YoKPJaBySbcADNoucagPK3hnvEvfkk7XFq1uSbrkvziexLWlQmH4K7sqS17lFga0fBW/FNCGATvDR5KZ7JYNzh9shsEWLDDPBeqiCH/49nZQkQB2H+RCk2kKLtyw==,iv:hDD1sWyp4tlrwc5owDThF1CnBtpPQ6rmWDFDNKW8tj8=,tag:AntTQ880dagnhOJWCPwaTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z6whdl8w2ymxrd2nu58sgwqz3le4qnnlpn8stkstpyxuctc27fhqwjpxjz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcHBlY1U4WDRqdWtmaVRn
            aWZiMERaYThtMFRzekVjNHBRd0ZtMTF5WUZRCk40c0k3aWdUMDRMbitxck5hY2Q2
            SXNXNHVTc1ZyT002VUNyd0J6L0NMaWcKLS0tIDhlaEdWamp2dXhVd0JoNjhvK29a
            L3NVaCtMaDA5U05aVkova2w5ZE1TMFkK86BxJ0fioB46zsKYWDbi+kw22XjPw45l
            6mFTYbIuCNdFAt9tv5MGoPbGHhCdXPw941QJ6h4p1YdXRnB3aSS70g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-01T22:44:38Z"
    mac: ENC[AES256_GCM,data:yENEB567spyUA6TdAwgcAhx8lNBCqgUduCCgyg133SqsHo2lTdNkA3J34QSgShFjsayUim2F0k+P5+PwhT9paMOm8g+2qQKmOKPSXSo8FI19ekDlQMq8NWvP+sbdLjapO4m5H+9mymjFP5/h2KinPPn7xEoCoDgkI6elq2J45Ls=,iv:cGs/ykRX/2Tgjm9cTlERLVl3yARhYDUkNGiP3Km2PYE=,tag:BiZu9oHRA6XvSsN72V5Oyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
